name: Cache Lama Docker Image

on: 
  schedule: 
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
    check-cache:
        runs-on: ubuntu-latest
        outputs:
          cache_found: ${{ steps.step1.outputs.noCache }}
        steps:
            - name: Retrieve Docker image
              uses: actions/cache/restore@v3
              with:
                path: lama-1-30.tar
                key: lama-1-30-${{ runner.os }}-

            - name: Check if Lama-docker was restored from cache
              id: step1
              run: |
                if [ -f lama-1-30.tar ]; then
                  echo "Lama's docker image is restored successfully. Exiting..."
                  echo "noCache=true" >> $GITHUB_OUTPUT
                else
                  echo "Cache not found. Building.."
                  echo "noCache=false" >> $GITHUB_OUTPUT
                fi
    
    build-image:
        needs: [check-cache]
        if: needs.check-cache.outputs.cache_found != 'true'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./.github/workflows/Dockerfile
                tags: berezun/lama-image:latest
                outputs: type=docker,dest=lama-1-30.tar

            - name: Cache Docker Lama file
              id: cache-file
              uses: actions/cache/save@v3
              with:
                path: lama-1-30.tar
                key: lama-1-30-${{ runner.os }}-
                restore-keys: |
                  lama-1-30-${{ runner.os }}-
